{% set name = "dimod" %}
{% set version = "0.10.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dimod-{{ version }}.tar.gz
  sha256: fb550db438b47debe9fa0c3192209e1f4a2109f9f77bf1f632f052927fbd5eae

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.21,<3.0
    - numpy >=1.19.1
    - pip
    - python
    - setuptools >=46.4.0
    - wheel
  run:
    - pyparsing >=2.4.7,<3.0.0
    - python
    - {{ pin_compatible('numpy') }}
  run_constrained:
    - dwave-preprocessing >=0.3,<0.4

test:
  imports:
    - dimod
    - dimod.testing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dimod
  summary: A shared API for binary quadratic model samplers.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
